// Generated by CoffeeScript 1.9.3
var convertToRomanNumeral;

convertToRomanNumeral = function(number) {
  var arabic, i, len, map, ref, result, roman;
  result = '';
  map = [[100, 'C'], [90, 'XC'], [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I']];
  for (i = 0, len = map.length; i < len; i++) {
    ref = map[i], arabic = ref[0], roman = ref[1];
    while (number >= arabic) {
      result = result.concat(roman);
      number -= arabic;
    }
  }
  return result;
};

describe('convertToRomanNumeral', function() {
  it('converts 1 to I', function() {
    var result;
    result = convertToRomanNumeral(1);
    return expect(result).toEqual('I');
  });
  it('converts 2 to II', function() {
    var result;
    result = convertToRomanNumeral(2);
    return expect(result).toEqual('II');
  });
  it('converts 3 to III', function() {
    var result;
    result = convertToRomanNumeral(3);
    return expect(result).toEqual('III');
  });
  it('converts 4 to IV', function() {
    var result;
    result = convertToRomanNumeral(4);
    return expect(result).toEqual('IV');
  });
  it('converts 5 to V', function() {
    var result;
    result = convertToRomanNumeral(5);
    return expect(result).toEqual('V');
  });
  it('converts 6 to VI', function() {
    var result;
    result = convertToRomanNumeral(6);
    return expect(result).toEqual('VI');
  });
  it("converts 7 to VII", function() {
    var result;
    result = convertToRomanNumeral(7);
    return expect(result).toEqual('VII');
  });
  it("converts 9 to IX", function() {
    var result;
    result = convertToRomanNumeral(9);
    return expect(result).toEqual('IX');
  });
  it("converts 10 to X", function() {
    var result;
    result = convertToRomanNumeral(10);
    return expect(result).toEqual('X');
  });
  it('converts 15 to XV', function() {
    var result;
    result = convertToRomanNumeral(15);
    return expect(result).toEqual('XV');
  });
  it('converts 20 to XX', function() {
    var result;
    result = convertToRomanNumeral(20);
    return expect(result).toEqual('XX');
  });
  it('converts 40 to XL', function() {
    var result;
    result = convertToRomanNumeral(40);
    return expect(result).toEqual('XL');
  });
  it('converts 47 to XLVII', function() {
    var result;
    result = convertToRomanNumeral(47);
    return expect(result).toEqual('XLVII');
  });
  it('converts 50 to L', function() {
    var result;
    result = convertToRomanNumeral(50);
    return expect(result).toEqual('L');
  });
  it('converts 90 to XC', function() {
    var result;
    result = convertToRomanNumeral(90);
    return expect(result).toEqual('XC');
  });
  return it('converts 100 to C', function() {
    var result;
    result = convertToRomanNumeral(100);
    return expect(result).toEqual('C');
  });
});
