// Generated by CoffeeScript 1.9.3
describe('Bowling', function() {
  var roll, rolls, score;
  rolls = null;
  beforeEach(function() {
    return rolls = [];
  });
  roll = function(pins) {
    return rolls = rolls.concat(pins);
  };
  score = function() {
    var fallen, i, len, result;
    result = 0;
    for (i = 0, len = rolls.length; i < len; i++) {
      fallen = rolls[i];
      result += fallen;
    }
    return result;
  };
  it('returns 0 for 20 gutter ball', function() {
    var i;
    for (i = 1; i <= 20; i++) {
      roll(0);
    }
    return expect(score()).toEqual(0);
  });
  it('returns 20 for 20 single pins knocked down', function() {
    var i;
    for (i = 1; i <= 20; i++) {
      roll(1);
    }
    return expect(score()).toEqual(20);
  });
  return it('returns 14 for [8, 2, 2] spare', function() {
    var i;
    roll(8);
    roll(2);
    roll(2);
    for (i = 1; i <= 17; i++) {
      roll(0);
    }
    return expect(score()).toEqual(14);
  });
});
